name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm install --force
      - run: rm -rf content/blog/*
      - run: node bin/for-actions.js
        env:
          DRIVE_FOLDER: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          OUTPUT_DIR: content/blog
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
